baseURL = "/"


[[redirects]]
  from = "/Redirect/Unibet"
  to = "https://dspk.kindredplc.com/redirect.aspx?pid=30964730&bid=34474"
  status = 301
  query = {path = "/Redirect/Unibet"}


  [[redirects]]
  from = "/Redirect/MrGreen"
  to = "https://ads.mrgreen.com/redirect.aspx?pid=4432076"
  status = 301
  query = {path = "/Redirect/MrGreen"}