baseURL = "/"

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

[[redirects]]
  from = "https://www.casinoniz.se"
  to = "https://www.casinoniz.se/"
  status = 301
  query = {path = "https://www.casinoniz.se"}


[[redirects]]
  from = "https://www.casinoniz.se/slotsons-laggerner"
  to = "https://www.casinoniz.se/nyheter/slotsons-laggerner"
  status = 301
  query = {path = "https://www.casinoniz.se/slotsons-laggerner"}


[[redirects]]
  from = "https://www.casinoniz.se/ninjacasino-aterkomst"
  to = "https://www.casinoniz.se/nyheter/ninjacasino-aterkomst"
  status = 301
  query = {path = "https://www.casinoniz.se/ninjacasino-aterkomst"}

[[redirects]]
  from = "/Go/unibet"
  to = "https://dspk.kindredplc.com/redirect.aspx?pid=30964730&bid=34474"
  status = 301
  query = {path = "/Go/unibet"}


  [[redirects]]
  from = "/Go/mrgreen"
  to = "https://ads.mrgreen.com/redirect.aspx?pid=4432076"
  status = 301
  query = {path = "/Go/mrgreen"}

    [[redirects]]
  from = "/Go/comeon"
  to = "https://media.comeon.com/tracking.php?tracking_code&aid=107839&mid=1753&sid=354226&pid=457"
  status = 301
  query = {path = "/Go/comeon"}

      [[redirects]]
  from = "/Go/nordicbet"
  to = "https://record.nordicbet.com/_zwvwrZh854rIUsd2cv5SdWNd7ZgqdRLk/1/"
  status = 301
  query = {path = "/Go/nordicbet"}


       [[redirects]]
  from = "/Go/mobilautomaten"
  to = "https://media.mobilautomaten.com/tracking.php?tracking_code&aid=107839&mid=1727&sid=354226&pid=410"
  status = 301
  query = {path = "/Go/mobilautomaten"}


           [[redirects]]
  from = "/Go/leovegas"
  to = "https://ads.leovegas.com/redirect.aspx?pid=3599439&bid=16049"
  status = 301
  query = {path = "/Go/leovegas"}

             [[redirects]]
  from = "/Go/casumo"
  to = "https://ads.casumoaffiliates.com/redirect.aspx?pid=1065670&bid=1906"
  status = 301
  query = {path = "/Go/casumo"}

             [[redirects]]
  from = "/Go/speedycasino"
  to = "https://media.heroaffiliates.com/redirect.aspx?pid=265765&bid=3252"
  status = 301
  query = {path = "/Go/speedycasino"}

               [[redirects]]
  from = "/Go/vera&john"
  to = "https://record.ppincome.net/_eTIfhuLY3wLQ5K5VC2FaW2Nd7ZgqdRLk/1/"
  status = 301
  query = {path = "/Go/vera&john"}

              [[redirects]]
  from = "/Go/888casino"
  to = "https://mmwebhandler.aff-online.com/c/43499?sr=1704316"
  status = 301
  query = {path = "/Go/888casino"}
  
                  [[redirects]]
  from = "/Go/bethard"
  to = "http://wleuroearners.adsrv.eacdn.com/C.ashx?btag=a_9093b_2758c_&affid=2853&siteid=9093&adid=2758&c="
  status = 301
  query = {path = "/Go/bethard"}

                    [[redirects]]
  from = "/Go/betsson"
  to = "https://record.betsson.com/_zwvwrZh854oK7p2EryfJhvwNd7ZgqdRLk/1/"
  status = 301
  query = {path = "/Go/betsson"}


                       [[redirects]]
  from = "/Go/betsafe"
  to = "https://record.betsafe.com/_zwvwrZh854oTfb_BYEk8c2Nd7ZgqdRLk/1/"
  status = 301
  query = {path = "/Go/betsafe "}

                        [[redirects]]
  from = "/Go/casinostugan"
  to = "https://media.casinostugan.com/tracking.php?tracking_code&aid=107839&mid=1718&sid=354226&pid=434"
  status = 301
  query = {path = "/Go/casinostugan"}

                        [[redirects]]
  from = "/Go/Guts"
  to = "http://wlguts.adsrv.eacdn.com/C.ashx?btag=a_15321b_2721c_&affid=4381&siteid=15321&adid=2721&c="
  status = 301
  query = {path = "/Go/Guts"}

                        [[redirects]]
  from = "/Go/thrills"
  to = "http://ads.thrillsaffiliates.com/redirect.aspx?pid=878163&bid=4977"
  status = 301
  query = {path = "/Go/thrills"}

                        [[redirects]]
  from = "/Go/rizk"
  to = "http://wlrizk.adsrv.eacdn.com/C.ashx?btag=a_15321b_1778c_&affid=4381&siteid=15321&adid=1778&c="
  status = 301
  query = {path = "/Go/rizk"}

                        [[redirects]]
  from = "/Go/casilando"
  to = "http://welcome.branders.partners/afs/come.php?id=4145&cid=19911&ctgid=1067&atype=1"
  status = 301
  query = {path = "/Go/casilando"}

                          [[redirects]]
  from = "/Go/casinoheroes"
  to = "https://media.heroaffiliates.com/redirect.aspx?pid=265765&bid=3219"
  status = 301
  query = {path = "/Go/casinoheroes"}

                          [[redirects]]
  from = "/Go/betway"
  to = "https://casino.betway.se/?s=bw204937&mid=82884"
  status = 301
  query = {path = "/Go/betway"}

                            [[redirects]]
  from = "/Go/noaccountcasino"
  to = "https://affiliatemedia.noaccountcasino.com/redirect.aspx?pid=4468&bid=1586&redirectURL=https://www.noaccountcasino.com/"
  status = 301
  query = {path = "/Go/noaccountcasino"}

                              [[redirects]]
  from = "/Go/frankfred"
  to = "https://www.frankfred.com/sv/?mid=868&sid=4125&aid=100550&pid=2"
  status = 301
  query = {path = "/Go/frankfred"}
  
                                [[redirects]]
  from = "/Go/snabbare"
  to = "https://media.snabbare.com/tracking.php?tracking_code&aid=107839&mid=1960&sid=354226&pid=635"
  status = 301
  query = {path = "/Go/snabbare"}

      [[redirects]]
  from = "/Go/hajper"
  to = "https://media.hajper.com/tracking.php?tracking_code&aid=107839&mid=1968&sid=354226&pid=640"
  status = 301
  query = {path = "/Go/hajper"}

        [[redirects]]
  from = "/Go/chanz"
  to = "http://wlchanz.adsrv.eacdn.com/C.ashx?btag=a_2934b_38c_&affid=828&siteid=2934&adid=38&c="
  status = 301
  query = {path = "/Go/chanz"}

         [[redirects]]
  from = "/Go/snabbis"
  to = "https://record.snabbisaffiliates.com/_nBB8jrTuRQUWqcfzuvZcQGNd7ZgqdRLk/1/"
  status = 301
  query = {path = "/Go/snabbis"}

           [[redirects]]
  from = "/Go/bingocom"
  to = "https://dspk.kindredplc.com/redirect.aspx?pid=30964730&bid=34158"
  status = 301
  query = {path = "/Go/bingocom"}

           [[redirects]]
  from = "/Go/pixelbet"
  to = "https://ads.pixel.bet/redirect.aspx?pid=3216&bid=1639"
  status = 301
  query = {path = "/Go/pixelbet"}

             [[redirects]]
  from = "/Go/highroller"
  to = "https://ads.highrolleraffiliates.com/redirect.aspx?pid=878163&bid=4911"
  status = 301
  query = {path = "/Go/highroller"}
  
               [[redirects]]
  from = "/Go/videoslots"
  to = "http://affiliates.videoslots.com/click/?campid=28396"
  status = 301
  query = {path = "/Go/videoslots"}

                 [[redirects]]
  from = "/Go/paf"
  to = "https://record.pafpartners.com/_Q3mqd8ZyuHNd0WQkpqTgsGNd7ZgqdRLk/1"
  status = 301
  query = {path = "/Go/paf"}

                   [[redirects]]
  from = "/Go/voodoodreams"
  to = "https://nvd.suprnation.com/redirect.aspx?pid=19381&bid=2244"
  status = 301
  query = {path = "/Go/voodoodreams"}

                    [[redirects]]
  from = "/Go/nyspins"
  to = "https://nvd.suprnation.com/redirect.aspx?pid=19381&bid=2245"
  status = 301
  query = {path = "/Go/nyspins"}

                      [[redirects]]
  from = "/Go/duelz"
  to = "https://nvd.suprnation.com/redirect.aspx?pid=19381&bid=2171"
  status = 301
  query = {path = "/Go/duelz"}

                        [[redirects]]
  from = "/Go/redkings"
  to = "https://site.gotocasinoredkings.com/index.php?aname=delshad"
  status = 301
  query = {path = "/Go/redkings"}

                          [[redirects]]
  from = "/Go/lunacasino"
  to = "http://site.lunacasino.com/index.php?aname=delshad&cg=swedish"
  status = 301
  query = {path = "/Go/lunacasino"}

                            [[redirects]]
  from = "/Go/eucasino"
  to = "https://site.gotoeucasino.com/index.php?aname=delshad&cg=swedish"
  status = 301
  query = {path = "/Go/eucasino"}

                              [[redirects]]
  from = "/Go/slotsmagic"
  to = "https://site.gotoslotsmagic.com/index.php?aname=delshad&cg=swedish"
  status = 301
  query = {path = "/Go/slotsmagic"}

                                [[redirects]]
  from = "/Go/ahtiGames"
  to = "https://site.ahtigames.com/index.php?aname=delshad&cg=swedish"
  status = 301
  query = {path = "/Go/ahtiGames"}

                                  [[redirects]]
  from = "/Go/drueckglueck"
  to = "https://site.gotodrueckglueck.com/index.php?aname=delshad&cg=swedish"
  status = 301
  query = {path = "/Go/drueckglueck"}

                                    [[redirects]]
  from = "/Go/karamba"
  to = "http://www.karamba.com/?AFI=12004&MMI=15189"
  status = 301
  query = {path = "/Go/karamba"}

        [[redirects]]
  from = "/Go/playojo"
  to = "https://site.gotoplayojo.com/index.php?aname=delshad&cg=swedish"
  status = 301
  query = {path = "/Go/playojo"}

          [[redirects]]
  from = "/Go/casinoroom"
  to = "http://play.ellmountgaming.com/redirect.aspx?pid=406800&bid=4680"
  status = 301
  query = {path = "/Go/casinoroom"}

            [[redirects]]
  from = "/Go/hyper"
  to = "http://affiliates.hypercasino.com/redirector?url=https://www.hypercasino.com&userid=1415&tracker=5531"
  status = 301
  query = {path = "/Go/hyper"}


                [[redirects]]
  from = "/Go/coolbet"
  to = "https://track.adform.net/C/?bn=33028607"
  status = 301
  query = {path = "/Go/coolbet"}

                  [[redirects]]
  from = "/Go/noaccountbet"
  to = "https://affiliatemedia.noaccountbet.com/redirect.aspx?pid=4468&bid=1589"
  status = 301
  query = {path = "/Go/noaccountbet"}


                    [[redirects]]
  from = "/Go/mariacasino"
  to = "https://dspk.kindredplc.com/redirect.aspx?pid=30964730&bid=34158"
  status = 301
  query = {path = "/Go/mariacasino"}

                      [[redirects]]
  from = "/Go/storspelare"
  to = "https://dspk.kindredplc.com/redirect.aspx?pid=30964730&bid=33276"
  status = 301
  query = {path = "/Go/storspelare"}

                       [[redirects]]
  from = "/Go/prankcasino"
  to = "https://www.prankcasino.com/sv?btag=655781_3DC9A875061F492B82D2728492433FEC"
  status = 301
  query = {path = "/Go/prankcasino"}


                           [[redirects]]
  from = "/Go/gogocasino"
  to = "https://www.gogocasino.com/"
  status = 301
  query = {path = "/Go/gogocasino"}



                             [[redirects]]
  from = "/Go/luckyvegas"
  to = "https://m.vegasfolks.com/Redirect.aspx?mid=4&sid=91&cid=XXX&pid=&affid=63"
  status = 301
  query = {path = "/Go/luckyvegas"}


                             [[redirects]]
  from = "/Go/inandoutbet"
  to = "http://wlinandoutbet.adsrv.eacdn.com/C.ashx?btag=a_17881b_1657c_&affid=5016&siteid=17881&adid=1657&c="
  status = 301
  query = {path = "/Go/inandoutbet"}


                               [[redirects]]
  from = "/Go/spinstationx"
  to = "http://wlivyaffiliates.adsrv.eacdn.com/C.ashx?btag=a_7131b_114c_&affid=1491&siteid=7131&adid=114&c="
  status = 301
  query = {path = "/Go/spinstationx"}

[[redirects]]
 from = "/Go/10bet"
  to = "https://track.10bet.com/C.ashx?btag=a_53735b_5382c_&affid=1680928&siteid=53735&adid=5382&c="
  status = 301
  query = {path = "/Go/10bet"}

[[redirects]]
 from = "/Go/casimba"
  to = "http://wlivyaffiliates.adsrv.eacdn.com/C.ashx?btag=a_7131b_374c_&affid=1491&siteid=7131&adid=374&c="
  status = 301
  query = {path = "/Go/casimba"}

  [[redirects]]
 from = "/Go/yobetit"
  to = "https://media.yoaffiliates.com/redirect.aspx?pid=3054&bid=2066"
  status = 301
  query = {path = "/Go/yobetit"}


   [[redirects]]
 from = "/Go/21casino"
  to = "https://welcome.twentyoneaffiliates.com/afs/come.php?cid=27871&ctgid=1044&atype=1&brandid=17"
  status = 301
  query = {path = "/Go/21casino"}


   [[redirects]]
 from = "/Go/luckycasino"
  to = "https://record.glitnoraffiliates.com/_RzGld47HRjDKto_EPcZApGNd7ZgqdRLk/1"
  status = 301
  query = {path = "/Go/luckycasino"}

    [[redirects]]
 from = "/Go/spincasino"
  to = "https://www.spincasino.se/?s=bfp20248&a=bfpadid116296"
  status = 301
  query = {path = "/Go/spincasino"}

 [[redirects]]
 from = "/Go/spela"
  to = "https://spela.tracking-genesisaffiliates.com/redirect.aspx?pid=108169&bid=4727"
  status = 301
  query = {path = "/Go/spela"}


 [[redirects]]
 from = "/Go/yoyocasino"
  to = "https://media.yoyocasino.se/redirect.aspx?pid=935227&lpid=14535&bid=6650"
  status = 301
  query = {path = "/Go/yoyocasino"}

  [[redirects]]
 from = "/Go/casinogods"
  to = "https://casinogods.tracking-genesisaffiliates.com/redirect.aspx?pid=108169&bid=6488"
  status = 301
  query = {path = "/Go/casinogods"}



  [[redirects]]
 from = "/Go/pelaa"
  to = "https://pelaa.tracking-genesisaffiliates.com/redirect.aspx?pid=108169&bid=5200"
  status = 301
  query = {path = "/Go/pelaa"}
  


[[redirects]]
 from = "/Go/jallacasino"
  to = "https://record.jallacasino.se/_zwvwrZh854oBdnrXAWEQVGNd7ZgqdRLk/1/"
  status = 301
  query = {path = "/Go/jallacasino"}
 


[[redirects]]
 from = "/Go/klirr"
  to = "https://record.epic.partners/_uUCqChjU8D4r8Syj4RJS-mNd7ZgqdRLk/1/"
  status = 301
  query = {path = "/Go/klirr"}

[[redirects]]
 from = "/Go/casinoplanet"
  to = "https://casinoplanet.tracking-genesisaffiliates.com/redirect.aspx?pid=108169&bid=8443"
  status = 301
  query = {path = "/Go/casinoplanet"}


